[package]
name = "tg_bot_test"
version = "0.1.0"
authors = ["Mateus Corrêa <mcorrea.comp@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
